// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/token_counting/v1/token_counting.proto

package token_countingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenCountingModel int32

const (
	TokenCountingModel_TOKEN_COUNTING_MODEL_UNSPECIFIED TokenCountingModel = 0
	TokenCountingModel_TOKEN_COUNTING_MODEL_GPT_5       TokenCountingModel = 1
)

// Enum value maps for TokenCountingModel.
var (
	TokenCountingModel_name = map[int32]string{
		0: "TOKEN_COUNTING_MODEL_UNSPECIFIED",
		1: "TOKEN_COUNTING_MODEL_GPT_5",
	}
	TokenCountingModel_value = map[string]int32{
		"TOKEN_COUNTING_MODEL_UNSPECIFIED": 0,
		"TOKEN_COUNTING_MODEL_GPT_5":       1,
	}
)

func (x TokenCountingModel) Enum() *TokenCountingModel {
	p := new(TokenCountingModel)
	*p = x
	return p
}

func (x TokenCountingModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenCountingModel) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_token_counting_v1_token_counting_proto_enumTypes[0].Descriptor()
}

func (TokenCountingModel) Type() protoreflect.EnumType {
	return &file_agynio_api_token_counting_v1_token_counting_proto_enumTypes[0]
}

func (x TokenCountingModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenCountingModel.Descriptor instead.
func (TokenCountingModel) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_token_counting_v1_token_counting_proto_rawDescGZIP(), []int{0}
}

type CountTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         TokenCountingModel     `protobuf:"varint,1,opt,name=model,proto3,enum=agynio.api.token_counting.v1.TokenCountingModel" json:"model,omitempty"`
	Messages      [][]byte               `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensRequest) Reset() {
	*x = CountTokensRequest{}
	mi := &file_agynio_api_token_counting_v1_token_counting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensRequest) ProtoMessage() {}

func (x *CountTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_token_counting_v1_token_counting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensRequest.ProtoReflect.Descriptor instead.
func (*CountTokensRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_token_counting_v1_token_counting_proto_rawDescGZIP(), []int{0}
}

func (x *CountTokensRequest) GetModel() TokenCountingModel {
	if x != nil {
		return x.Model
	}
	return TokenCountingModel_TOKEN_COUNTING_MODEL_UNSPECIFIED
}

func (x *CountTokensRequest) GetMessages() [][]byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CountTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []int32                `protobuf:"varint,1,rep,packed,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensResponse) Reset() {
	*x = CountTokensResponse{}
	mi := &file_agynio_api_token_counting_v1_token_counting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensResponse) ProtoMessage() {}

func (x *CountTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_token_counting_v1_token_counting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensResponse.ProtoReflect.Descriptor instead.
func (*CountTokensResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_token_counting_v1_token_counting_proto_rawDescGZIP(), []int{1}
}

func (x *CountTokensResponse) GetTokens() []int32 {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_agynio_api_token_counting_v1_token_counting_proto protoreflect.FileDescriptor

const file_agynio_api_token_counting_v1_token_counting_proto_rawDesc = "" +
	"\n" +
	"1agynio/api/token_counting/v1/token_counting.proto\x12\x1cagynio.api.token_counting.v1\"x\n" +
	"\x12CountTokensRequest\x12F\n" +
	"\x05model\x18\x01 \x01(\x0e20.agynio.api.token_counting.v1.TokenCountingModelR\x05model\x12\x1a\n" +
	"\bmessages\x18\x02 \x03(\fR\bmessages\"-\n" +
	"\x13CountTokensResponse\x12\x16\n" +
	"\x06tokens\x18\x01 \x03(\x05R\x06tokens*Z\n" +
	"\x12TokenCountingModel\x12$\n" +
	" TOKEN_COUNTING_MODEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTOKEN_COUNTING_MODEL_GPT_5\x10\x012\x8a\x01\n" +
	"\x14TokenCountingService\x12r\n" +
	"\vCountTokens\x120.agynio.api.token_counting.v1.CountTokensRequest\x1a1.agynio.api.token_counting.v1.CountTokensResponseBIZGgithub.com/agynio/api/gen/agynio/api/token_counting/v1;token_countingv1b\x06proto3"

var (
	file_agynio_api_token_counting_v1_token_counting_proto_rawDescOnce sync.Once
	file_agynio_api_token_counting_v1_token_counting_proto_rawDescData []byte
)

func file_agynio_api_token_counting_v1_token_counting_proto_rawDescGZIP() []byte {
	file_agynio_api_token_counting_v1_token_counting_proto_rawDescOnce.Do(func() {
		file_agynio_api_token_counting_v1_token_counting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_token_counting_v1_token_counting_proto_rawDesc), len(file_agynio_api_token_counting_v1_token_counting_proto_rawDesc)))
	})
	return file_agynio_api_token_counting_v1_token_counting_proto_rawDescData
}

var file_agynio_api_token_counting_v1_token_counting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agynio_api_token_counting_v1_token_counting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agynio_api_token_counting_v1_token_counting_proto_goTypes = []any{
	(TokenCountingModel)(0),     // 0: agynio.api.token_counting.v1.TokenCountingModel
	(*CountTokensRequest)(nil),  // 1: agynio.api.token_counting.v1.CountTokensRequest
	(*CountTokensResponse)(nil), // 2: agynio.api.token_counting.v1.CountTokensResponse
}
var file_agynio_api_token_counting_v1_token_counting_proto_depIdxs = []int32{
	0, // 0: agynio.api.token_counting.v1.CountTokensRequest.model:type_name -> agynio.api.token_counting.v1.TokenCountingModel
	1, // 1: agynio.api.token_counting.v1.TokenCountingService.CountTokens:input_type -> agynio.api.token_counting.v1.CountTokensRequest
	2, // 2: agynio.api.token_counting.v1.TokenCountingService.CountTokens:output_type -> agynio.api.token_counting.v1.CountTokensResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agynio_api_token_counting_v1_token_counting_proto_init() }
func file_agynio_api_token_counting_v1_token_counting_proto_init() {
	if File_agynio_api_token_counting_v1_token_counting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_token_counting_v1_token_counting_proto_rawDesc), len(file_agynio_api_token_counting_v1_token_counting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_token_counting_v1_token_counting_proto_goTypes,
		DependencyIndexes: file_agynio_api_token_counting_v1_token_counting_proto_depIdxs,
		EnumInfos:         file_agynio_api_token_counting_v1_token_counting_proto_enumTypes,
		MessageInfos:      file_agynio_api_token_counting_v1_token_counting_proto_msgTypes,
	}.Build()
	File_agynio_api_token_counting_v1_token_counting_proto = out.File
	file_agynio_api_token_counting_v1_token_counting_proto_goTypes = nil
	file_agynio_api_token_counting_v1_token_counting_proto_depIdxs = nil
}
