// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agynio/api/token_counting/v1/token_counting.proto

package token_countingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenCountingService_CountTokens_FullMethodName = "/agynio.api.token_counting.v1.TokenCountingService/CountTokens"
)

// TokenCountingServiceClient is the client API for TokenCountingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenCountingService counts tokens for model-specific message payloads.
type TokenCountingServiceClient interface {
	CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResponse, error)
}

type tokenCountingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenCountingServiceClient(cc grpc.ClientConnInterface) TokenCountingServiceClient {
	return &tokenCountingServiceClient{cc}
}

func (c *tokenCountingServiceClient) CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountTokensResponse)
	err := c.cc.Invoke(ctx, TokenCountingService_CountTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenCountingServiceServer is the server API for TokenCountingService service.
// All implementations should embed UnimplementedTokenCountingServiceServer
// for forward compatibility.
//
// TokenCountingService counts tokens for model-specific message payloads.
type TokenCountingServiceServer interface {
	CountTokens(context.Context, *CountTokensRequest) (*CountTokensResponse, error)
}

// UnimplementedTokenCountingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenCountingServiceServer struct{}

func (UnimplementedTokenCountingServiceServer) CountTokens(context.Context, *CountTokensRequest) (*CountTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountTokens not implemented")
}
func (UnimplementedTokenCountingServiceServer) testEmbeddedByValue() {}

// UnsafeTokenCountingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenCountingServiceServer will
// result in compilation errors.
type UnsafeTokenCountingServiceServer interface {
	mustEmbedUnimplementedTokenCountingServiceServer()
}

func RegisterTokenCountingServiceServer(s grpc.ServiceRegistrar, srv TokenCountingServiceServer) {
	// If the following call panics, it indicates UnimplementedTokenCountingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenCountingService_ServiceDesc, srv)
}

func _TokenCountingService_CountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenCountingServiceServer).CountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenCountingService_CountTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenCountingServiceServer).CountTokens(ctx, req.(*CountTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenCountingService_ServiceDesc is the grpc.ServiceDesc for TokenCountingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenCountingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.token_counting.v1.TokenCountingService",
	HandlerType: (*TokenCountingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountTokens",
			Handler:    _TokenCountingService_CountTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/token_counting/v1/token_counting.proto",
}
